apiVersion: v1
kind: Service
metadata:
  name: kuliber-chat-socket
spec:
  selector:
    app: kuliber-chat-socket
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuliber-chat-socket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuliber-chat-socket
  template:
    metadata:
      labels:
        app: kuliber-chat-socket
    spec:
      containers:
        - name: kuliber-chat-socket
          image: learnk8s/knote-js:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always